import type { Metadata } from "next";
import { fontNotoSansJp, fontNotoSansMono } from "@/app/fonts/fonts";
// import localFont from "next/font/local";
import "./globals.css";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// if (process.env.NODE_ENV === "development") {
//   import("@/mocks/browser").then(({ worker }) => worker.start());
// }

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* <body
        className={`${geistSans.variable} ${geistMono.variable} ${fontNotoSansJp.variable} antialiased`}
      > */}
      <body className={`${fontNotoSansJp.variable} ${fontNotoSansMono.variable}`}>{children}</body>
    </html>
  );
}
